import os
from typing import Dict, Any, Optional

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    from groq import Groq
except ImportError:
    Groq = None


class LLMExplainerError(Exception):
    """Base exception for LLM Explainer failures."""
    pass


class LLMExplainerConfigError(LLMExplainerError):
    """Raised when Groq API key or required environment configuration is missing."""
    pass


class LLMExplainer:
    """
    Person 3 AI Layer Component:
    Groq LLM-powered explanation generator for structured governance decisions.
    
    IMPORTANT ARCHITECTURAL GUARDRAILS:
    - This module is strictly an EXPLANATION layer for human operators.
    - It NEVER makes governance decisions, alters verdicts, or runs policy logic.
    - Person 1's Governance API remains the sole authoritative decision-maker.
    """

    SYSTEM_PROMPT = (
        "You are an explanation generator for a financial-agent governance system.\n"
        "You do not make governance decisions.\n"
        "The supplied governance decision is authoritative.\n"
        "Explain the decision using only the provided structured data.\n"
        "Never invent missing information.\n"
        "Never change or question the verdict.\n"
        "Do not provide financial advice.\n"
        "Do not recommend whether the transaction should have been allowed.\n"
        "Return only a concise explanation (1-3 sentences) suitable for a governance dashboard."
    )

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None
    ):
        if Groq is None:
            raise LLMExplainerConfigError(
                "The 'groq' package is not installed. Please run 'pip install groq'."
            )

        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        if not self.api_key:
            raise LLMExplainerConfigError(
                "GROQ_API_KEY environment variable is missing. "
                "Please set GROQ_API_KEY in your environment or .env file."
            )

        self.model = model or os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        self.client = Groq(api_key=self.api_key)

    def generate_explanation(
        self,
        response_data: Dict[str, Any],
        action_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generates a concise, grounded human-readable explanation for a governance outcome.
        
        Args:
            response_data: Dictionary containing fields from Person 1's ActionResponse
                           (verdict, policy_passed, spend_cap_passed, reason, agent_id, etc.)
            action_data: Optional dictionary containing ActionRequest fields
                         (action_type, amount, currency, recipient, description, context)
                         
        Returns:
            String containing the plain-English explanation generated by Groq.
        """
        action_info = action_data or {}

        agent_id = response_data.get("agent_id") or action_info.get("agent_id", "unknown-agent")
        action_type = action_info.get("action_type") or response_data.get("action_type", "unspecified_action")
        amount = action_info.get("amount") if "amount" in action_info else response_data.get("amount", 0.0)
        currency = action_info.get("currency") or response_data.get("currency", "INR")
        verdict = response_data.get("verdict", "UNKNOWN")
        policy_passed = response_data.get("policy_passed", False)
        spend_cap_passed = response_data.get("spend_cap_passed", True)
        reason = response_data.get("reason", "No reason provided.")

        user_prompt = (
            "<structured_governance_data>\n"
            f"Agent ID: {agent_id}\n"
            f"Action Type: {action_type}\n"
            f"Amount: {currency} {amount}\n"
            f"Verdict: {verdict}\n"
            f"Policy Passed: {policy_passed}\n"
            f"Spend Cap Passed: {spend_cap_passed}\n"
            f"Governance Reason: {reason}\n"
            "</structured_governance_data>\n\n"
            "Please generate a clear, concise human-readable explanation of this governance decision."
        )

        try:
            completion = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.1,
                max_tokens=250
            )

            explanation = completion.choices[0].message.content.strip()
            return explanation

        except Exception as e:
            # Safe error logging without exposing API key
            error_msg = f"Groq LLM Explanation Service Error: {str(e)}"
            raise LLMExplainerError(error_msg) from e
